# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: walstream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'walstream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwalstream.proto\x12\x0cwalstream.v1\"\x94\x02\n\x0c\x43hangeRecord\x12\x0b\n\x03lsn\x18\x01 \x01(\t\x12\x13\n\x0b\x63ommit_time\x18\x02 \x01(\x03\x12\r\n\x05table\x18\x03 \x01(\t\x12\x11\n\toperation\x18\x04 \x01(\t\x12\x30\n\x03old\x18\x05 \x03(\x0b\x32#.walstream.v1.ChangeRecord.OldEntry\x12\x30\n\x03new\x18\x06 \x03(\x0b\x32#.walstream.v1.ChangeRecord.NewEntry\x1a*\n\x08OldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a*\n\x08NewEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01J\x04\x08\x32\x10\x65\"\xa6\x01\n\rReplayRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12)\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x1a.walstream.v1.ChangeRecord\x12\x14\n\x0cvirtual_time\x18\x03 \x01(\x03\x12\x15\n\roriginal_time\x18\x04 \x01(\x03\x12\x14\n\x0cspeed_factor\x18\x05 \x01(\x02\x12\x17\n\x0fidempotency_key\x18\x06 \x01(\t\"I\n\x0eReplayResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rwas_duplicate\x18\x03 \x01(\x08\"\x0f\n\rHealthRequest\"\x96\x01\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12@\n\ncomponents\x18\x02 \x03(\x0b\x32,.walstream.v1.HealthResponse.ComponentsEntry\x1a\x31\n\x0f\x43omponentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x99\x01\n\x08Replayer\x12H\n\x0bReplayEvent\x12\x1b.walstream.v1.ReplayRequest\x1a\x1c.walstream.v1.ReplayResponse\x12\x43\n\x06Health\x12\x1b.walstream.v1.HealthRequest\x1a\x1c.walstream.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'walstream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANGERECORD_OLDENTRY']._loaded_options = None
  _globals['_CHANGERECORD_OLDENTRY']._serialized_options = b'8\001'
  _globals['_CHANGERECORD_NEWENTRY']._loaded_options = None
  _globals['_CHANGERECORD_NEWENTRY']._serialized_options = b'8\001'
  _globals['_HEALTHRESPONSE_COMPONENTSENTRY']._loaded_options = None
  _globals['_HEALTHRESPONSE_COMPONENTSENTRY']._serialized_options = b'8\001'
  _globals['_CHANGERECORD']._serialized_start=34
  _globals['_CHANGERECORD']._serialized_end=310
  _globals['_CHANGERECORD_OLDENTRY']._serialized_start=218
  _globals['_CHANGERECORD_OLDENTRY']._serialized_end=260
  _globals['_CHANGERECORD_NEWENTRY']._serialized_start=262
  _globals['_CHANGERECORD_NEWENTRY']._serialized_end=304
  _globals['_REPLAYREQUEST']._serialized_start=313
  _globals['_REPLAYREQUEST']._serialized_end=479
  _globals['_REPLAYRESPONSE']._serialized_start=481
  _globals['_REPLAYRESPONSE']._serialized_end=554
  _globals['_HEALTHREQUEST']._serialized_start=556
  _globals['_HEALTHREQUEST']._serialized_end=571
  _globals['_HEALTHRESPONSE']._serialized_start=574
  _globals['_HEALTHRESPONSE']._serialized_end=724
  _globals['_HEALTHRESPONSE_COMPONENTSENTRY']._serialized_start=675
  _globals['_HEALTHRESPONSE_COMPONENTSENTRY']._serialized_end=724
  _globals['_REPLAYER']._serialized_start=727
  _globals['_REPLAYER']._serialized_end=880
# @@protoc_insertion_point(module_scope)
