# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import walstream_pb2 as walstream__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in walstream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplayerStub(object):
    """==========================================================================
    Services (Internal gRPC only)
    ==========================================================================

    Replayer service handles the actual replay of events to target systems.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReplayEvent = channel.unary_unary(
                '/walstream.v1.Replayer/ReplayEvent',
                request_serializer=walstream__pb2.ReplayRequest.SerializeToString,
                response_deserializer=walstream__pb2.ReplayResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/walstream.v1.Replayer/Health',
                request_serializer=walstream__pb2.HealthRequest.SerializeToString,
                response_deserializer=walstream__pb2.HealthResponse.FromString,
                _registered_method=True)


class ReplayerServicer(object):
    """==========================================================================
    Services (Internal gRPC only)
    ==========================================================================

    Replayer service handles the actual replay of events to target systems.
    """

    def ReplayEvent(self, request, context):
        """Replay a single event with idempotency enforcement.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplayerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReplayEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplayEvent,
                    request_deserializer=walstream__pb2.ReplayRequest.FromString,
                    response_serializer=walstream__pb2.ReplayResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=walstream__pb2.HealthRequest.FromString,
                    response_serializer=walstream__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'walstream.v1.Replayer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('walstream.v1.Replayer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Replayer(object):
    """==========================================================================
    Services (Internal gRPC only)
    ==========================================================================

    Replayer service handles the actual replay of events to target systems.
    """

    @staticmethod
    def ReplayEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/walstream.v1.Replayer/ReplayEvent',
            walstream__pb2.ReplayRequest.SerializeToString,
            walstream__pb2.ReplayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/walstream.v1.Replayer/Health',
            walstream__pb2.HealthRequest.SerializeToString,
            walstream__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
